run:
  deadline: 10m10s

issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - errcheck
    - exportloopref
    - gocritic
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - typecheck
    - unconvert
    - unused
    - whitespace

  # don't enable:
  #  - asciicheck
  #  - depguard
  #  - dogsled
  #  - dupl
  #  - funlen
  #  - gochecknoinits
  #  - gochecknoglobals
  #  - gocognit
  #  - goconst
  #  - gocyclo
  #  - gomnd
  #  - godot
  #  - godox
  #  - goerr113
  #  - lll
  #  - nakedret
  #  - prealloc
  #  - revive
  #  - stylecheck
  #  - staticcheck
  #  - structcheck
  #  - testpackage
  #  - unparam
  #  - wsl

linters-settings:
  errcheck:
    ignore: fmt:.*,io:Close,github.com/sacloud/autoscaler/logging:.*
