before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/sacloud/autoscaler/version.Revision={{.ShortCommit}}
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    binary: '{{ .ProjectName }}'
archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Os }}-{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_SHA256SUMS'
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      - "--local-user"
      - "E37EC0B895A9AC27DC4919AB96CEB4B93D86849D"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
# brews:
#   - tap:
#       owner: sacloud
#       name: homebrew-usacloud
#       token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
#     url_template: "https://github.com/sacloud/usacloud/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
#     commit_author:
#       name: Usacloud
#       email: sacloud.users@gmail.com
#     homepage: "https://github.com/sacloud/usacloud"
#     license: "Apache 2.0"
#     # for debug
#     # skip_upload: true
#     test: |
#       system "#{bin}/usacloud --version"
changelog:
  skip: true
