// Copyright 2021 The sacloud Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by "stringer -type=JobTypes"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[JobTypeUnknown-0]
	_ = x[JobTypeUp-1]
	_ = x[JobTypeDown-2]
}

const _JobTypes_name = "JobTypeUnknownJobTypeUpJobTypeDown"

var _JobTypes_index = [...]uint8{0, 14, 23, 34}

func (i JobTypes) String() string {
	if i < 0 || i >= JobTypes(len(_JobTypes_index)-1) {
		return "JobTypes(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _JobTypes_name[_JobTypes_index[i]:_JobTypes_index[i+1]]
}
